spring:
  application:
    name: api-gateway
  redis:
    host: 192.168.0.17
    port: 6379
    password: 123456
    
    
    
server:
  port: 7082
  
zuul:
  #全部服务忽略敏感头（全部服务都可传递cookie）
  sensitive-headers:  
  routes:
    aaaa:    #myProduct自定义路由名称
      path: /myProduct/**  #转发源地址
      serviceId: product   #转发目的地址
      sensitiveHeaders:     #设置空，不过滤其他东西cookie
    #简洁写法  项目名称：转发地址
    #product: /myProduct/**


  #不允许外部访问的接口地址
  ignored-patterns:
    - /myProduct/product1/list
    - /**/product1/list  #通配符写法
    

