spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://192.168.0.254:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
      show-sql: true
  rabbitmq:
      host:  192.168.0.254
      port: 5672
      username: admin
      password: admin
  redis:
    host: 192.168.0.17
    port: 6379
    password: 123456


#访问应用的名字，修改 均衡器规则，IRule接口1
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

server:
  port: 7080
  
env:
  dev15251076311
girl:
  name: lili
  age: 10
