spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
      show-sql: true
  rabbitmq:
      host:  127.0.0.1
      port: 5672
      username: guest
      password: guest
  redis:
    host: 116.62.163.66
    port: 5800
    password: c13h4@Liu


#访问应用的名字，修改 均衡器规则，IRule接口1
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

server:
  port: 7080
  
env:
  dev55521111111
girl:
  name: lili
  age: 10
