spring:
  application:
    name: product
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://192.168.0.254:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
      show-sql: true
  rabbitmq:
      host: 192.168.0.254
      port: 5672
      username: admin
      password: admin



server:
  port: 7081
  
env:
  dev55521111111
